// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNVEJfzM_HM0KCNLy3RaTzE_jYNH3JRGo',
    appId: '1:916505893813:web:b1ab9713c65a65fafb57fc',
    messagingSenderId: '916505893813',
    projectId: 'ru-app-af5a1',
    authDomain: 'ru-app-af5a1.firebaseapp.com',
    storageBucket: 'ru-app-af5a1.appspot.com',
    measurementId: 'G-XFHK69STGK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAb4d-EmqMoVdsEp_XtZSrgYjXufYNWDDc',
    appId: '1:916505893813:android:02b6769f52c417d5fb57fc',
    messagingSenderId: '916505893813',
    projectId: 'ru-app-af5a1',
    storageBucket: 'ru-app-af5a1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjxD7_Ycb0c02dehvyILUtW2grA3O_lVM',
    appId: '1:916505893813:ios:27f8683034b43c45fb57fc',
    messagingSenderId: '916505893813',
    projectId: 'ru-app-af5a1',
    storageBucket: 'ru-app-af5a1.appspot.com',
    iosClientId: '916505893813-5de5ka9l0jq4qfe3l7hvash42296127s.apps.googleusercontent.com',
    iosBundleId: 'com.rudigital.ios',
  );
}
